"""empty message

Revision ID: 25e6af2520cd
Revises: 86f942c9bd9a
Create Date: 2024-08-13 10:38:33.681430

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25e6af2520cd'
down_revision = '86f942c9bd9a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_details', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_dob', sa.DATE(), nullable=False))
        batch_op.add_column(sa.Column('gender', sa.CHAR(), nullable=False))
        batch_op.drop_column('Gender')
        batch_op.drop_column('user_DOB')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_details', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_DOB', sa.DATE(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('Gender', sa.CHAR(length=1), autoincrement=False, nullable=False))
        batch_op.drop_column('gender')
        batch_op.drop_column('user_dob')

    # ### end Alembic commands ###
