"""empty message

Revision ID: 86599d65b8d0
Revises: 25e6af2520cd
Create Date: 2024-08-13 11:25:39.361294

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86599d65b8d0'
down_revision = '25e6af2520cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_details', schema=None) as batch_op:
        batch_op.alter_column('user_dob',
               existing_type=sa.DATE(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_details', schema=None) as batch_op:
        batch_op.alter_column('user_dob',
               existing_type=sa.DATE(),
               nullable=False)

    # ### end Alembic commands ###
