"""empty message

Revision ID: 86f942c9bd9a
Revises: 
Create Date: 2024-08-12 16:35:41.865292

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86f942c9bd9a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products_table',
    sa.Column('prod_id', sa.Integer(), nullable=False),
    sa.Column('prod_name', sa.String(length=224), nullable=False),
    sa.Column('prod_price', sa.Integer(), nullable=False),
    sa.Column('prod_desc', sa.String(length=224), nullable=False),
    sa.Column('Category', sa.String(length=224), nullable=False),
    sa.Column('prod_type', sa.String(length=224), nullable=False),
    sa.Column('discount', sa.Integer(), nullable=False),
    sa.Column('weight', sa.Integer(), nullable=False),
    sa.Column('ratings', sa.Integer(), nullable=False),
    sa.Column('prod_img', sa.String(length=224), nullable=False),
    sa.PrimaryKeyConstraint('prod_id')
    )
    op.create_table('user_details',
    sa.Column('user_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_name', sa.String(length=30), nullable=False),
    sa.Column('user_address', sa.String(length=225), nullable=False),
    sa.Column('phn_no', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('user_DOB', sa.DATE(), nullable=False),
    sa.Column('Gender', sa.CHAR(), nullable=False),
    sa.Column('prof_pic', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('cart',
    sa.Column('relation_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('prod_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['prod_id'], ['products_table.prod_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user_details.user_id'], ),
    sa.PrimaryKeyConstraint('relation_id')
    )
    op.create_table('transactions',
    sa.Column('trans_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('trans_type', sa.String(), nullable=True),
    sa.Column('trans_date', sa.Date(), nullable=True),
    sa.Column('trans_status', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user_details.user_id'], ),
    sa.PrimaryKeyConstraint('trans_id')
    )
    op.create_table('order_details',
    sa.Column('ord_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('prod_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('prod_status', sa.String(length=25), nullable=True),
    sa.Column('deli_date', sa.Date(), nullable=False),
    sa.Column('trans_id', sa.Integer(), nullable=True),
    sa.Column('deli_status', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['prod_id'], ['products_table.prod_id'], ),
    sa.ForeignKeyConstraint(['trans_id'], ['transactions.trans_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user_details.user_id'], ),
    sa.PrimaryKeyConstraint('ord_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('order_details')
    op.drop_table('transactions')
    op.drop_table('cart')
    op.drop_table('user_details')
    op.drop_table('products_table')
    # ### end Alembic commands ###
